name: Build, Test, and Deploy Next.js App to Azure Web App

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  

      - name: Install dependencies
        run: |
          cd reelio-frontend
          npm install

      - name: Run ESLint
        run: |
          cd reelio-frontend
          npm run lint


  build_and_test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd reelio-frontend
          npm install


  build_and_push_container:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: https://reeliocr.azurecr.io/
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      # Build and push container image
      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./reelio-frontend
          push: true
          tags: reeliocr.azurecr.io/reelio-frontend:${{ github.sha }}
          file: ./reelio-frontend/Dockerfile
          enviroment: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}


  deploy_to_azure:
    runs-on: ubuntu-latest
    needs: build_and_push_container
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'reelio'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_PUBLISH }}
          images: 'reeliocr.azurecr.io/reelio-frontend:${{ github.sha }}'