# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - reelio-staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://reeliocr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9d488dcfde684bfc940c17d8dd1e356c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_47934a5ed42549309de470fc687c9d3d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: reeliocr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9d488dcfde684bfc940c17d8dd1e356c }}/reelio-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'reelio-staging'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3fb1f726a05f4a2fb86b73c086f6f7b7 }}
        images: 'reeliocr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9d488dcfde684bfc940c17d8dd1e356c }}/reelio-frontend:${{ github.sha }}'